#!/bin/bash

scripts="$1"
if [ "$scripts" == "" ]
then
	exit 1
fi

enabled="$scripts/EFFECTS_ARE_ENABLED"
if [ ! -f "$enabled" ]
then
	touch "$enabled"
fi

source "$scripts/effects"
bash "$scripts/$start" "$scripts"

