#!/bin/bash

scripts="$1"
if [ "$scripts" == "" ]
then
	exit 1
fi

which compton > /dev/null
if [ "$?" == "0" ]
then
	stop="compton-stop"
else
	stop="xcompmgr-stop"
fi

bash "$scripts/$stop" "$scripts"

