#!/bin/bash

scripts="$1"
if [ "$scripts" == "" ]
then
	exit 1
fi

which compton > /dev/null
if [ "$?" == "0" ]
then
	start="compton-start"
else
	start="xcompmgr-start"
fi

bash "$scripts/$start" "$scripts"

