#!/bin/bash

class=$1
width=$2
height=$3

function increase {
	current=$1
	width=$2
	height=$3
	target=$(( ($width - $patch) * ($height - $patch) ))

	if [ $current -lt $target ]
	then
		echo "ResizeMove frame ${width}p ${height}p 50-50w 50-50w"
		exit
	fi
}

patch=0
if [ "$class" = "XTerm" ]
then
	patch=13
fi

current=$(( $width * $height ))

echo "Raise"

increase $current 800 600
increase $current 960 600
increase $current 1024 768
increase $current 1280 1024

echo "Maximize True 100 100"

