#!/bin/bash

class=$1
width=$2
height=$3

source "${mtp_scripts}/window-size-workaround"

function increase {
	current=$1
	width=$2
	height=$3
	target=$(( $width * $height ))

	if [ "$class" = "XTerm" ]
	then
		target=$(( $target - ($target / 100 * 10) ))
	fi

	if [ $current -lt $target ]
	then
		echo "ResizeMove ${width}p ${height}p 50-50w 50-50w"
		exit
	fi
}

current=$(( $width * $height ))

echo "Raise"

increase $current 800 600
increase $current 960 600
increase $current 1024 768
increase $current 1280 1024

echo "Maximize True 100 100"

