#!/bin/bash

ps ax | grep -q '[x]compmgr[^-]'
if [ "$?" == "0" ]
then
	# xcompmgr is already running.
	exit 0
fi

if [ "$1" == "" ]
then
	exit 1
fi

scripts="$1"
enabled="$scripts/XCOMPMGR_IS_ENABLED"

if [ ! -f "$enabled" ]
then
	exit 0
fi

xcompmgr -c -C -r7 -l-10 -t-10 -o.75 &

