#!/bin/bash

scripts="$1"
if [ "$scripts" == "" ]
then
	exit 1
fi

enabled="$scripts/XCOMPMGR_IS_ENABLED"
if [ ! -f "$enabled" ]
then
	touch "$enabled"
fi

touch "$enabled"

bash "$scripts/xcompmgr-start" "$scripts"

