#!/bin/bash

ps ax | grep -v grep | grep -v xcompmgr- | grep -q xcompmgr
if [ "$?" == "0" ]
then
	# xcompmgr is already running.
	exit 0
fi

if [ "$1" == "" ]
then
	exit 1
fi

MTP_SCRIPTS="$1"
XCOMPMGR_IS_ENABLED="$MTP_SCRIPTS/XCOMPMGR_IS_ENABLED"

if [ ! -f "$XCOMPMGR_IS_ENABLED" ]
then
	exit 0
fi

xcompmgr -c -C -r7 -l-10 -t-10 -o.75 &

