#!/bin/bash

if [ "$1" == "" ]
then
	exit 1
fi

MTP_SCRIPTS="$1"
XCOMPMGR_IS_ENABLED="$MTP_SCRIPTS/XCOMPMGR_IS_ENABLED"

if [ -f "$XCOMPMGR_IS_ENABLED" ]
then
	rm "$XCOMPMGR_IS_ENABLED"
fi

bash "$MTP_SCRIPTS/xcompmgr-stop" "$MTP_SCRIPTS"

